version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '6500:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  postgresDB:
